### PR TITLE
Make build run

### PR DESCRIPTION
**Pull request by forki**
I tried to make it run on my machine. Needed to go a bit down with the target framework. Also made it use paket magic mode. But now I'm lost `src\elmish\*` seems to be missing.

image

### CODE REVIEW

**Comment by forki** [comment]
tried to link the files via github links. still no touchdown

**Comment by forki** [comment]
yay! now it builds!

**Comment by 2sComplement** [comment]
Paket and framework updates look great.

Elmish sources were intended to be pulled in as a submodule. Did you try `git submodule --init --recursive`?

**Comment by forki** [comment]
It's your project but could you please try without submodules?!
Using github deps might be a good alternative here

**Comment by forki** [comment]
(it's all automated in this way)

**Comment by 2sComplement** [comment]
Can you pin to a specific commit?

**Comment by forki** [comment]
look at the lockfile. it's pinned to a commit

**Comment by 2sComplement** [comment]
Ah cool, I only looked at the dependencies file earlier. Sure we can give this a try.

**Pull request merged**
