### PR TITLE
Bug Fix: bindings using two way validate now update the UI upon model…

### PR DESCRIPTION
**Pull request by huwmanatee**
Hi, as discussed in [issue 19](https://github.com/Prolucid/Elmish.WPF/issues/19). Here is a pull request which addresses the issue.

### CODE REVIEW

**Comment by 2sComplement** [comment]
Thanks!

**Comment by huwmanatee** [comment]
Can you republish the nuget package? Is there a automated build etc?

**Comment by 2sComplement** [comment]
Haven't set up CI yet. I just pushed 1.0.0-beta-7. Thanks again!

**Comment by huwmanatee** [comment]
And thank you.
I am happy to assist with your future plans for this lib.

**Pull request merged**
